# Biblioteca numpy

## array

In [ ]:
import numpy
obj = numpy.array([1, 2, 3])
print(type(obj))
print(obj)
print(obj.ndim)
print(obj.size)

## arange

In [11]:
import numpy
obj =numpy. arange(6)
print (obj)

obj = numpy. arange (1, 6)
print (obj)

obj = numpy. arange (1, 6, 2)
print (obj)

[0 1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]


## reshape

In [12]:
import numpy
obj = numpy.arange(6)
print(obj)

print(obj.reshape (2, 3))

print(obj.reshape(3,2))


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [13]:
import numpy
print (numpy.zeros ((3)))

print (numpy.zeros((3,4)))

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
import numpy
print(numpy.full((3, 2), 20.0))
print(numpy.full((2,3),1/3))

[[20. 20.]
 [20. 20.]
 [20. 20.]]
[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]


In [15]:
import numpy
A = numpy. array ( [ [10 , 9, 8], [1, 2, 3]])
print (A [0, :])

print (A[1, :])

[10  9  8]
[1 2 3]


In [16]:
import numpy
A = numpy. array ( [ [10 , 9, 8], [1, 2, 3]])
print (A[:, 1:3])

print (A[:, 0:2])

[[9 8]
 [2 3]]
[[10  9]
 [ 1  2]]
