# Exercício 4 – NumPy

Utilizando a biblioteca **NumPy**:

**a.** Cria um array de números `1` com shape `(8, 2)`

**b.** Cria um array de `zeros` com shape `(5, 7)`

**c.** Subtrai o novo array de outro com dados aleatórios e armazena-o numa variável chamada `subarray`

**d.** Calcula a média dos valores do array `subarray`


***

In [2]:
import numpy as np

#### a) Array de uns com shape (8, 2)

In [4]:
array_uns = np.ones((8, 2))
print('Array de uns (8x2):')
print(array_uns)

Array de uns (8x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### b) Array de zeros com shape (5, 7)

In [5]:
array_zeros = np.zeros((5, 7))
print('Array de zeros (5x7):')
print(array_zeros)

Array de zeros (5x7):
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [8]:
array_zeros.shape

(5, 7)

#### c) Subtrair array_zeros de um array com dados aleatórios do mesmo shape

In [10]:
x, y = array_zeros.shape

# números aleatórios entre 0 e 1
# com as mesmas dimensões que o array de zeros
array_random = np.random.rand(x, y)  

subarray =  array_zeros - array_random
print('Subarray (aleatório - zeros):')
print(subarray)

Subarray (aleatório - zeros):
[[-0.08183016 -0.98352619 -0.35133388 -0.15746847 -0.75922648 -0.61492048
  -0.57445154]
 [-0.64951616 -0.68424966 -0.13791886 -0.9174299  -0.18869388 -0.55115402
  -0.32537141]
 [-0.13512307 -0.95965588 -0.07947257 -0.29158809 -0.0074041  -0.92406793
  -0.54500011]
 [-0.68819062 -0.46560164 -0.67094817 -0.15574848 -0.44499045 -0.95974667
  -0.81325632]
 [-0.17707473 -0.82893355 -0.42844201 -0.24594532 -0.79304272 -0.90909516
  -0.20194436]]


#### d) Média dos valores do array subarray

In [11]:
media = np.mean(subarray)
print(f'Média dos valores do subarray: {media}')

Média dos valores do subarray: -0.5057818009374854


### End of File