# Exercício 4 –  - FAV Enunciado Geral

Utilizando a biblioteca **NumPy**:

**a.** Cria um array de números `1` com shape `(8, 2)`

**b.** Cria um array de `zeros` com shape `(5, 7)`

**c.** Subtrai o novo array de outro com dados aleatórios e armazena-o numa variável chamada `subarray`

**d.** Calcula a média dos valores do array `subarray`


***

In [12]:
import numpy as np

#### a) Array de uns com shape (8, 2)

In [13]:
array_uns = np.ones((8, 2))
print('Array de uns (8x2):')
print(array_uns)

Array de uns (8x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#### b) Array de zeros com shape (5, 7)

In [14]:
array_zeros = np.zeros((5, 7))
print('Array de zeros (5x7):')
print(array_zeros)

Array de zeros (5x7):
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [15]:
array_zeros.shape

(5, 7)

#### c) Subtrair array_zeros de um array com dados aleatórios do mesmo shape

In [16]:
x, y = array_zeros.shape

# números aleatórios entre 0 e 1
# com as mesmas dimensões que o array de zeros
array_random = np.random.rand(x, y)  

subarray =  array_zeros - array_random
print('Subarray (aleatório - zeros):')
print(subarray)

Subarray (aleatório - zeros):
[[-0.84968602 -0.0634227  -0.04397749 -0.32248077 -0.53859414 -0.74406917
  -0.56068249]
 [-0.85041562 -0.41443828 -0.67503223 -0.56828928 -0.8999682  -0.7547419
  -0.51405651]
 [-0.97949815 -0.70906243 -0.16308872 -0.68956502 -0.8873281  -0.00746852
  -0.2918544 ]
 [-0.63414109 -0.67635734 -0.56193623 -0.85845772 -0.30401668 -0.10778713
  -0.15077844]
 [-0.0210384  -0.46778027 -0.20810795 -0.49005196 -0.97975387 -0.50067001
  -0.11576802]]


#### d) Média dos valores do array subarray

In [17]:
media = np.mean(subarray)
print(f'Média dos valores do subarray: {media}')

Média dos valores do subarray: -0.5029818643756423


### End of File